version: 2

models:
  - name: dim_movies
    description: Dimension table for cleansed movie metadata
    columns:
      - name: movie_id
        description: Primary key of the movie
        tests:
          - not_null

      - name: movie_title
        description: Standardized movie title
        tests:
          - not_null

      - name: genre_array
        description: List of genres in array format

      - name: genres
        description: Raw genre string from sources

  - name: dim_users
    description: Dimension table of unique users from both ratings and tags
    columns:
      - name: user_id
        description: Unique user identifier
        tests:
          - not_null

  - name: dim_genome_tags
    description: Dimension table for genome tag metadata
    columns:
      - name: tag_id
        description: Unique tag identifier
        tests:
          - not_null

      - name: tag
        description: Raw tag string from dataset
        tests:
          - not_null

  - name: dim_links
    description: Dimension table mapping movies to external sources like IMDB and TMDB
    columns:
      - name: movie_id
        description: Foreign key to dim_movies
        tests:
          - not_null

      - name: imdb_id
        description: IMDB identifier
        tests:
          - not_null

      - name: tmdb_id
        description: TMDB identifier
        tests:
          - not_null
